Add sepolia client
subvisual/wordle3 pull request #25
Opened 2024-11-11 11:14 UTC by rccsousa

## Why
In order to test Wordle3 on Sepolia Testnet to be able to interact with the game publicly and polish smart contract interaction.
## How
By updating wagmi configs to add a sepolia testnet bridge and refactoring smart contract interaction by using wagmi `useWriteContract` hooks.

2024-11-11 11:15 UTC, rccsousa commented on frontend/src/App.css
> +  max-width: 80%;
fixes readability (was too small)

2024-11-11 11:16 UTC, rccsousa commented on frontend/src/App.jsx
> +        }
moved places

2024-11-11 11:17 UTC, rccsousa commented on frontend/src/App.jsx
> +    }, [address, isConfirmed])
updated to listen for confirmations (when user is interacting with wallet)

2024-11-11 14:52 UTC, DavideSilva commented on src/ERC20.sol
> +    address public owner = msg.sender;
This works? I'm not sure this is correct as `msg.sender` only has a value when called from a transaction. You can declare the variable without initialising it

2024-11-11 14:55 UTC, DavideSilva requested changes
Break this down into smaller PR's please. Lots of changes here that are not related to the PR title or description. It's getting messy and it's becoming difficult to review

2024-11-11 14:55 UTC, rccsousa commented on src/ERC20.sol
> +    address public owner = msg.sender;
It's working, yes, but shouldn't be there. 
I'll re-review all the submited code.

2024-11-11 17:28 UTC, DavideSilva commented on frontend/src/App.jsx
> +//TODO: Remove after testing import { AlreadyPlayed } from './components/AlreadyPlayed/AlreadyPlayed'
Is this meant to be here?

2024-11-12 15:56 UTC, DavideSilva approved these changes

2024-11-12 17:53 UTC, merged